version: '3.9'

services:
  db:
    image: postgres:15
    container_name: smartfridge-db
    environment:
      POSTGRES_USER: smartfridge
      POSTGRES_PASSWORD: smartfridge
      POSTGRES_DB: smartfridge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartfridge"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: smartfridge-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://smartfridge:smartfridge@db:5432/smartfridge
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  ai:
    build:
      context: ./ai
    container_name: smartfridge-ai
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: smartfridge-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ai

volumes:
  pgdata:
